
requiredVars = { ...
    'pv_all','Vs_all','H_all','den_all', ...
    'trainIdxFull','valIdxFull','testIdxFull', ...
    'best_params','flen','outputVsDim','outputHDim','outputTotal', ...
    'vs_half','rho_half'};

for k = 1:numel(requiredVars)
    if ~exist(requiredVars{k}, 'var')
        error('缺少变量: %s，请先 load 多模态工作区数据。', requiredVars{k});
    end
end


normalize   = @(x, xmin, xmax) (x - xmin)./(xmax - xmin + eps);
denormalize = @(x, xmin, xmax) x.*(xmax - xmin) + xmin;
Vs_min = min(Vs_all(:,1:outputVsDim),[],'all');
Vs_max = max(Vs_all(:,1:outputVsDim),[],'all');

H_min  = min(H_all(:,1:outputHDim),[],'all');
H_max  = max(H_all(:,1:outputHDim),[],'all');

pv_min = min(pv_all,[],1);
pv_max = max(pv_all,[],1);


pv_norm_all = normalize(pv_all, pv_min, pv_max);

N_valid = size(pv_all,1);

XFull = cell(N_valid,1);
for i = 1:N_valid
    XFull{i} = pv_norm_all(i,:);  
end


YNormFull = [normalize(Vs_all(:,1:outputVsDim), Vs_min, Vs_max), ...
             normalize(H_all(:,1:outputHDim),  H_min,  H_max)];


XTrainFull = XFull(trainIdxFull);
YTrainFull = YNormFull(trainIdxFull,:);

XValFull   = XFull(valIdxFull);
YValFull   = YNormFull(valIdxFull,:);

XTestFull  = XFull(testIdxFull);
YTestFull  = YNormFull(testIdxFull,:);

rho_train_full = den_all(trainIdxFull,:);
rho_val_full   = den_all(valIdxFull,:);
rho_test_full  = den_all(testIdxFull,:);

rho_all = [rho_train_full; rho_val_full];   


lr = best_params(1);

nCNN = round(best_params(2));
kernelSize = round(best_params(3));
baseChannel = round(best_params(4)/16)*16;

nLSTM = round(best_params(5));
baseHidden = round(best_params(6)/16)*16;
maxHidden = 1024;


%% ================= 全局变量 =================
global HighContrast_Vs_RMSE_history Vs_RMSE_history

HighContrast_Vs_RMSE_history = [];
Vs_RMSE_history = [];

layers = [
    sequenceInputLayer( ...
        1, ...
        'Name', 'input', ...
        'Normalization', 'none', ...
        'MinLength', flen)
];

channel = baseChannel;

for c = 1:nCNN

    layers = [
        layers
        convolution1dLayer( ...
            kernelSize, ...
            channel, ...
            'Padding', 'same', ...
            'Name', sprintf('conv%d', c))
        batchNormalizationLayer( ...
            'Name', sprintf('bn%d', c))
        reluLayer( ...
            'Name', sprintf('relu%d', c))
        maxPooling1dLayer( ...
            2, ...
            'Stride', 2, ...
            'Name', sprintf('pool%d', c))
    ];

    channel = min(channel * 2, 1024);
end

hidden = baseHidden;

for l = 1:nLSTM

    layers = [
        layers
        lstmLayer( ...
            hidden, ...
            'OutputMode', 'last', ...
            'Name', sprintf('lstm%d', l))
    ];

    hidden = min(hidden * 2, 1024);
end

layers = [
    layers
    fullyConnectedLayer( ...
        outputTotal, ...
        'Name', 'fc')
];

net = dlnetwork(layers);
numEpochs = 100;
miniBatchSize = 64;
learnRate = lr;

trailingAvg = [];
trailingAvgSq = [];
iteration = 0;

numTrain = numel(XTrainFull);

TrainLossHistory = [];
ValLossHistory = [];

customLossLayer = customRegressionLayer( ...
    'normMSEWeighted', ...
    Vs_min, ...
    Vs_max, ...
    H_min, ...
    H_max, ...
    rho_all, ...
    vs_half, ...
    rho_half, ...
    false);

for epoch = 1:numEpochs


    idx = randperm(numTrain);

    for i = 1:miniBatchSize:numTrain

        iteration = iteration + 1;

        batchIdx = idx( ...
            i:min(i + miniBatchSize - 1, numTrain));

  
        XBatch = XTrainFull(batchIdx);
        YBatch = YTrainFull(batchIdx, :);

        dlX = dlarray( ...
            cat(3, XBatch{:}), ...
            'CTB');

        dlY = dlarray( ...
            YBatch', ...
            'CB');


        [loss, grads] = dlfeval( ...
            @(net, dlX, dlY) modelLossCustom( ...
                net, ...
                dlX, ...
                dlY, ...
                customLossLayer), ...
            net, ...
            dlX, ...
            dlY);


        [net, trailingAvg, trailingAvgSq] = adamupdate( ...
            net, ...
            grads, ...
            trailingAvg, ...
            trailingAvgSq, ...
            iteration, ...
            learnRate);

        TrainLossHistory(end + 1) = ...
            double(extractdata(loss));
    end

    dlXVal = dlarray( ...
        cat(3, XValFull{:}), ...
        'CTB');

    dlYPredVal = forward(net, dlXVal);

    YPred_norm = extractdata(dlYPredVal)';


    dlYVal = dlarray( ...
        YValFull', ...
        'CB');

    valLossDL = customLossLayer.forwardLoss( ...
        dlYPredVal, ...
        dlYVal);

    valLoss = double(extractdata(valLossDL));

    ValLossHistory(end + 1) = valLoss;

    YPred_Vs = ...
        YPred_norm(:, 1:outputVsDim) .* ...
        (Vs_max - Vs_min) + Vs_min;

    YTrue_Vs = ...
        YValFull(:, 1:outputVsDim) .* ...
        (Vs_max - Vs_min) + Vs_min;

    diffVs = YPred_Vs - YTrue_Vs;

    Vs_RMSE = sqrt( ...
        mean(diffVs(:).^2, 'omitnan'));

    Vs_RMSE_history(end + 1) = Vs_RMSE;

    nLayer = min([
        size(YPred_Vs, 2), ...
        size(YTrue_Vs, 2), ...
        size(rho_val_full, 2)
    ]);

    if nLayer < 2

        highContrastVsRMSE = 0;

    else


        Vs_pred_trim = ...
            YPred_Vs(:, 1:nLayer);

        Vs_true_trim = ...
            YTrue_Vs(:, 1:nLayer);

        rho_trim = ...
            rho_val_full(:, 1:nLayer);


        Z = rho_trim .* Vs_true_trim;


        Z_ratio = ...
            Z(:, 1:end-1) ./ ...
            (Z(:, 2:end) + eps);

        threshold = 1.05;

        highContrastMask = ...
            Z_ratio > threshold;


        dV = ...
            Vs_pred_trim(:, 1:end-1) - ...
            Vs_true_trim(:, 1:end-1);

        if any(highContrastMask(:))

            selectedError = ...
                dV(highContrastMask);


            selectedError = ...
                selectedError(isfinite(selectedError));

            if isempty(selectedError)

                highContrastVsRMSE = 0;

            else

                highContrastVsRMSE = sqrt( ...
                    mean(selectedError.^2));

            end

        else

            highContrastVsRMSE = 0;

        end
    end

    HighContrast_Vs_RMSE_history(end + 1) = ...
        highContrastVsRMSE;

    recentStart = max( ...
        numel(TrainLossHistory) - 9, ...
        1);

    recentTrainLoss = mean( ...
        TrainLossHistory(recentStart:end), ...
        'omitnan');

    fprintf([ ...
        '[Epoch %d/%d] ', ...
        'TrainLoss %.4e | ', ...
        'ValLoss %.4e | ', ...
        'VsRMSE %.3f | ', ...
        'HC-Vs-RMSE %.3f\n'], ...
        epoch, ...
        numEpochs, ...
        recentTrainLoss, ...
        valLoss, ...
        Vs_RMSE, ...
        highContrastVsRMSE);
end

dlXTest = dlarray( ...
    cat(3, XTestFull{:}), ...
    'CTB');

dlYPredTest = forward(net, dlXTest);

YPredTest_norm = extractdata(dlYPredTest)';

YPredTest = zeros(size(YPredTest_norm));

YPredTest(:, 1:outputVsDim) = denormalize( ...
    YPredTest_norm(:, 1:outputVsDim), ...
    Vs_min, ...
    Vs_max);


YPredTest(:, outputVsDim + 1:end) = denormalize( ...
    YPredTest_norm(:, outputVsDim + 1:end), ...
    H_min, ...
    H_max);


YTrueTest_Vs = denormalize( ...
    YTestFull(:, 1:outputVsDim), ...
    Vs_min, ...
    Vs_max);

YTrueTest_H = denormalize( ...
    YTestFull(:, outputVsDim + 1:end), ...
    H_min, ...
    H_max);

YPredTest_Vs = ...
    YPredTest(:, 1:outputVsDim);

YPredTest_H = ...
    YPredTest(:, outputVsDim + 1:end);

Vs_RMSE_test = sqrt( ...
    mean( ...
        (YPredTest_Vs(:) - YTrueTest_Vs(:)).^2, ...
        'omitnan'));

H_RMSE_test = sqrt( ...
    mean( ...
        (YPredTest_H(:) - YTrueTest_H(:)).^2, ...
        'omitnan'));


